import Foundation

/// One speaker turn in a captured meeting. `speakerIndex` is a diarized
/// cluster index (0 is always the microphone track — the user — everything
/// else is "voice N" from the system-audio track), not a real identity;
/// `speakerName` is nil until the user labels it themselves in the
/// Notetaker page. Chirp has no way to know a participant's name on its
/// own — the LinkedIn-style enrichment Wispr Flow's Notetaker uses for
/// this is a network lookup about someone else, which doesn't fit an
/// on-device app and was deliberately left out.
struct MeetingSegment: Codable, Equatable, Identifiable {
    var id = UUID()
    var speakerIndex: Int
    var speakerName: String?
    var text: String
    var startTime: TimeInterval
    var endTime: TimeInterval
    /// This segment's own voice embedding from `DiarizerManager` — kept
    /// (it's a ~256-float vector, not audio, and not reversible to it) so
    /// that renaming a speaker can enroll their voice in
    /// `KnownSpeakerStore` for next time, without needing to keep the
    /// original recording around to re-derive it later. Optional so notes
    /// saved before this field existed still decode.
    var embedding: [Float]?
}

/// One action item pulled out of a meeting by `MeetingSummarizer`, with a
/// completion state the user can toggle in the Notetaker detail sheet —
/// plain read-only text until this existed.
struct ActionItem: Codable, Equatable, Identifiable {
    var id = UUID()
    var text: String
    var isDone: Bool = false

    init(text: String, isDone: Bool = false) {
        self.text = text
        self.isDone = isDone
    }

    private enum CodingKeys: String, CodingKey { case id, text, isDone }

    /// Notes saved before checkboxes existed stored each action item as a
    /// plain string — decode either shape so an old note still loads
    /// instead of the whole `[MeetingNote]` array silently failing to
    /// decode and every past meeting vanishing with it.
    init(from decoder: Decoder) throws {
        if let single = try? decoder.singleValueContainer(), let text = try? single.decode(String.self) {
            self.text = text
            self.isDone = false
            return
        }
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        text = try container.decode(String.self, forKey: .text)
        isDone = try container.decodeIfPresent(Bool.self, forKey: .isDone) ?? false
    }
}

struct MeetingNote: Codable, Identifiable, Equatable {
    let id: UUID
    var title: String
    var date: Date
    var duration: TimeInterval
    /// The captured app, if `MeetingDetector` recognized one — resolved to
    /// a name/icon the same way Insights already resolves
    /// `HistoryEntry.targetBundleID`.
    var appBundleID: String?
    /// The matching Calendar event's own title, if EventKit found one —
    /// often more useful than `title` alone ("Weekly Sync" vs. "Zoom
    /// Meeting, 2:00 PM").
    var calendarTitle: String?
    var segments: [MeetingSegment]
    /// Generated by `MeetingSummarizer` from `segments` via the same
    /// on-device `RewriteEngine` Ask Chirp and Voice Profile already use.
    /// Nil until that pass completes (or if it's never run — Apple
    /// Intelligence unavailable, say).
    var summary: String?
    var decisions: [String]
    var actionItems: [ActionItem]

    init(
        id: UUID = UUID(), title: String, date: Date, duration: TimeInterval,
        appBundleID: String? = nil, calendarTitle: String? = nil,
        segments: [MeetingSegment] = [], summary: String? = nil,
        decisions: [String] = [], actionItems: [ActionItem] = []
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.duration = duration
        self.appBundleID = appBundleID
        self.calendarTitle = calendarTitle
        self.segments = segments
        self.summary = summary
        self.decisions = decisions
        self.actionItems = actionItems
    }

    /// What `MeetingSummarizer` and the Notetaker detail page both read —
    /// each labeled turn on its own line, in order.
    var transcriptText: String {
        segments.map { segment in
            let label = segment.speakerName ?? "Speaker \(segment.speakerIndex + 1)"
            return "\(label): \(segment.text)"
        }.joined(separator: "\n")
    }

    var wordCount: Int {
        segments.reduce(0) { $0 + $1.text.split(whereSeparator: { $0.isWhitespace }).count }
    }

    /// Everything in the detail sheet as one block of plain text — summary,
    /// decisions, action items (with their checked state), then the full
    /// transcript — for pasting into an email or doc in one paste rather
    /// than copying the transcript and retyping the rest by hand.
    var formattedNoteText: String {
        var parts: [String] = [title]
        if let summary, !summary.isEmpty {
            parts.append("Summary\n\(summary)")
        }
        if !decisions.isEmpty {
            parts.append("Decisions\n" + decisions.map { "- \($0)" }.joined(separator: "\n"))
        }
        if !actionItems.isEmpty {
            parts.append("Action items\n" + actionItems.map {
                "- [\($0.isDone ? "x" : " ")] \($0.text)"
            }.joined(separator: "\n"))
        }
        parts.append("Transcript\n\(transcriptText)")
        return parts.joined(separator: "\n\n")
    }
}

/// Persists captured meeting notes — same on-disk JSON pattern as
/// `HistoryStore`, just keyed by a real `UUID` instead of a derived string
/// id, since two meetings can plausibly start in the same second where two
/// dictations sharing a timestamp-derived id essentially can't.
final class MeetingNoteStore {
    private(set) var notes: [MeetingNote] = []
    /// More generous than `HistoryStore`'s own 30 days: a meeting someone
    /// wants to search back through has a longer natural shelf life than a
    /// quick dictation.
    private let retentionDays = 90
    private var fileURL: URL {
        AppPaths.supportDirectory.appendingPathComponent("meeting_notes.json")
    }

    init() {
        if let data = try? Data(contentsOf: fileURL),
           let saved = try? JSONDecoder().decode([MeetingNote].self, from: data) {
            notes = saved.sorted { $0.date > $1.date }
            prune()
            save()
        }
    }

    func add(_ note: MeetingNote) {
        notes.insert(note, at: 0)
        prune()
        save()
    }

    func update(_ note: MeetingNote) {
        guard let index = notes.firstIndex(where: { $0.id == note.id }) else { return }
        notes[index] = note
        save()
    }

    func delete(id: UUID) {
        notes.removeAll { $0.id == id }
        save()
    }

    private func prune() {
        guard let cutoff = Calendar.current.date(byAdding: .day, value: -retentionDays, to: Date())
        else { return }
        notes.removeAll { $0.date < cutoff }
    }

    private func save() {
        if let data = try? JSONEncoder().encode(notes) {
            try? data.write(to: fileURL, options: .atomic)
        }
    }
}
